### ISSUE TITLE
[BUG] All UTXO chain gas has been hard coded to 20 Sats/vbyte

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix#124]
Currently , in the new UI , when sending assets, gas has been hardcoded to 20 sats / vbyte , which is wrong.

**Expected Behaviour:**
The app should talk to block explorer to find out current gas price , and pay accordingly.

![image](https://github.com/voltix-vault/voltix/assets/749608/d504eaa5-f543-4b4a-b3b5-484947b53735)

**Comment by enriquesouza** [comment]
I am also looking into this one
