### ISSUE TITLE
[BUG] MAX button logic on send screen is incorrect

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix#133]
On Send screen , when user click "MAX" button , currently it just fill it with user's whole balance , which is incorrect.

<img width="924" alt="image" src="https://github.com/voltix-vault/voltix/assets/749608/a7a3e000-040b-476e-82e3-fdfbcf30b911">

Expected Result: The app need to figure out the gas fee for the transaction , and deduct the transaction fee from the max value
You can call `UTXOChainsHelper.getBitcoinTransactionPlan`  to get the transaction plan , which will return the estimated Fee

**Comment by enriquesouza** [comment]
Working on it.

**Comment by enriquesouza** [comment]
I believe we should show the actual fee instead of the sats per byte when we get it from the tx plan.

**Comment by enriquesouza** [comment]
Fixed for all chains
