### ISSUE TITLE
[BUG] When broadcast transaction , if the server return "already known" , it should mark the transaction as success

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix#139]
For example , when broadcast ETH transaction , when the same transaction already exist in Mempool , it will return the following error
```
 {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"already known"}}
```

We need to parse the error message , if the return message from server is like above , it means one of the device already broadcast the transaction to blockchain correctly, it should display as success

**Comment by enriquesouza** [comment]
I will take a look at this one.
