### ISSUE TITLE
[Optimization] - Use Wei instead of Gwei

### ISSUE THREAD

**Issue by enriquesouza** [voltix-vault/voltix#155]
We should change the system to use Wei (or the token decimals) instead of Gwei.

It will reduce the number of conversations around the system.

If we need to convert to sign a tx we can do it only where we need it. 

This will reduce the complexity of the code and the number of conversions

**Comment by johnnyluo** [comment]
The amount get from blockchain , it is always in Wei , we only convert it to Gwei / ETH when display it to user.

**Comment by enriquesouza** [comment]
I reopened it since we need the amounts in Wei, we were using Gwei, but L2 uses fractions for fees, for example, 0.02 GWEI

**Comment by enriquesouza** [comment]
Done
