### ISSUE TITLE
[Bug] Send amount view ui bugs

### ISSUE THREAD

**Issue by flypaper0** [voltix-vault/voltix#171]
- [ ] Amount field does not allow comma `,` entry. Dot `.` works
- [ ] Continue button should have clear background

**Comment by Rockindash** [comment]
@flypaper0 can you clarify the second point??

**Comment by flypaper0** [comment]
@Rockindash  Look at the view around Continue button. It overlay screens content

<img  width=300 src="https://github.com/voltix-vault/voltix/assets/5384197/8ebce6ae-986c-42f5-87c0-e59e9ac9b0ed">

**Comment by Rockindash** [comment]
Oh that, that is intensional in order to avoid overcrowding between the button and underlying fields.
