### ISSUE TITLE
UX Issues

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#182]
# Identify SELF on tx list

- [x]  DONE

* if `isSelf(address)`, then list as `SELF`

<img width="509" alt="Screenshot 2024-04-03 at 7 04 04 am" src="https://github.com/voltix-vault/voltix/assets/41815753/deb2fd47-199d-42b2-8e06-629bef801339">

# All `addresss` `txId` is hyper-linked (open browser)

- [x]  DONE

Anywhere display address or txID, display as cyan colour and deep link (tap)

* vault view
* tx list
* finish tx

* `{explorer}/address/{addresss}`
* `{explorer}/tx/{txID}`

<img width="508" alt="Screenshot 2024-04-03 at 6 48 21 am" src="https://github.com/voltix-vault/voltix/assets/41815753/d7440005-3448-4cc2-bb8d-6eeff0eba143">
<img width="509" alt="Screenshot 2024-04-03 at 6 49 06 am" src="https://github.com/voltix-vault/voltix/assets/41815753/b1d651c6-dec8-4a23-a44b-a97b1c430f91">

# Tap Chain Vault Row goes to Chain Detail View

- [x]  DONE

* Currently: Tap Vault Row opens up vault pane in same view
* Problem: Too much detail for one small space
* Desired: Tap Vault Row slides to new Detail Page

<img width="1153" alt="Screenshot 2024-04-03 at 6 53 45 am" src="https://github.com/voltix-vault/voltix/assets/41815753/3a79cacd-5973-40a3-85b3-650682586b54">

# Chain Vault Row Should Show Summary, not Actions

- [ ]  DONE

* Current: Chain Vault Row shows Action Buttons
* Problem: Too cramped
* Desired: Show Summary only, Move Action buttons to Chain Detail View

- If only `1 asset` hide the pill (like Bitcoin); instead show total balance of single asset
- If multiple assets `3 assets`; 
- No Action Buttons
- `$TOTAL VALUE`

<img width="1225" alt="Screenshot 2024-04-03 at 6 56 46 am" src="https://github.com/voltix-vault/voltix/assets/41815753/4e10c177-dd43-499f-adbd-100429d9d377">

# Unnecessary Camera Screen

- [x]  DONE

* Current: When tap `CAMERA` button, a preview screen comes up; uses taps again
* Problem: Not necessary
* Desired: Show Camera immediately have text overlay at top 

```
SCAN OTHER DEVICE TO PAIR
```

<img width="500" alt="Screenshot 2024-04-03 at 7 01 31 am" src="https://github.com/voltix-vault/voltix/assets/41815753/01e8a81a-2f32-4fb1-b22a-3f8111ed67d3">

# Smaller `CHOOSE CHAINS` button

- [x]  DONE

* Current Choose Chains is too visually large
* Desired: Smaller `+ Choose Chains` button

<img width="1222" alt="Screenshot 2024-04-03 at 7 07 51 am" src="https://github.com/voltix-vault/voltix/assets/41815753/ec87cbde-f9d8-49f8-9cdf-f1a73ba706b0">

# Split `+ CHOOSE CHAINS` and `+ CHOOSE TOKENS`

- [ ]  DONE

* Current: Chains and Tokens are in same list 
* Problem: Too cramped when have many assets
* Desired: `+ CHOOSE CHAINS` on Vault Summary View only turns chains on/off
* Vault Detail View: `+ CHOOSE TOKENS` is filtered list only tokens for that chain

<img width="511" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/57c53792-2d82-4126-8d6f-f7b1d6a2d0a8">

# Device Select List is Cards (not ROW)

- [x]  DONE

* Current: Device Select list (very important) too visually small
* Desired: Render as large icons, `iPad` `iPhone` like icons; easy to select

<img width="475" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/9d25efe5-b1eb-41d5-9bf5-dd605953abf5">

**Comment by Rockindash** [comment]
For Identify SELF on tx list and All addresss txId is hyper-linked (open browser)
Its a good idea to add a link action button on the right or making the entire row tappable. Since text with underline is more of website's flow to open a link. For mobile apps, the target area needs to be broader.

**Comment by Rockindash** [comment]
For Smaller CHOOSE CHAINS button comment.
I would suggest sticking to the current design since its a primary action and tap area needs to wider (at least 44px). Also left aligning it makes it unsymmetrical.

**Comment by jpthor** [comment]
@Rockindash Disagree - currently we have two competing Primary Actions
"choose chains"
and
"camera keysign join"

The more important one is keysign Camera; CHOOSE CHAINS should be secondary, because when a user sets their desired chain/tokens choices, they won't need to change it much. 

<img width="522" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/1d203d93-ea65-42a5-ae58-b05eb654f36c">
