### ISSUE TITLE
Keysgin (Joining using QrCode)

### ISSUE THREAD

**Issue by enriquesouza** [voltix-vault/voltix#190]
There is an issue when pairing devices. We scan the QR code using a physical device to join and sign the transaction. 

It shows on the list of the discovered devices, but it was not joined. So I had to hit the button again to join, and the signature fails.

**Comment by enriquesouza** [comment]
<img width="503" alt="image" src="https://github.com/voltix-vault/voltix/assets/1700699/ad4af207-b64c-4e06-819e-d45a73d7c22d">

![image](https://github.com/voltix-vault/voltix/assets/1700699/e84afd69-ee51-4142-a685-f8305a9caf0d)

**Comment by johnnyluo** [comment]
I believe this issue has been fixed , if you see this one again , feel free to reopen it
