### ISSUE TITLE
Vault Details

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#203]
# Background

User needs to know the vault parties to remind them

# Implementation

- [x] done

When creating a vault, each device shares the vault arrangement to local
- other parties
- number

# Device Details in Menu

- [x] done

In Menu, add "Device Details"
- Device Type
- Name
- Pubkey

# Export

- [x] done

When export vault:
- pass vault details for export
- other parties
- number of other parties

# UI

- [x]  done

on this screen at top add Vault Details > row
list other parties known for the other vault
```
2 of 3 Vault
1) iPad 6 (pub key)
2) iPhone 12 mini  (pub key)
3) iPhone 13  (pub key)
```

<img width="341" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/4d4279c9-5379-4c76-b90e-5e08d6097fd7">

# Vault Gen

- [x] done

when selecting other parties, remind user what type of vault it is `2 of 3` `3 of 4` etc
- depending on number the choose

<img width="336" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/132f13d3-bbcb-4488-bd12-86b433f648b0">

**Comment by johnnyluo** [comment]
The keygen parties are available in `vault.signers`
