### ISSUE TITLE
Always Select SELF on KeyGen/KeySign

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#211]
# Always select self, and do not show in list

- [x]  done

Only show the other devices in list

# When select other device, increment the vault type

- [x] done

1) If only select one, it is `2 of 2 vault`
2) If select two, it is `2 of 3 vault`
3) If select three, it is `3 of 4 vault`
etc

<img width="336" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/ab3a4231-2026-429a-bd11-16dc67c7f9eb">

# When complete sign, return back to inside VAULT 

- [x] done

Currently it goes to MAIN vault screen

**Comment by johnnyluo** [comment]
#225

**Comment by johnnyluo** [comment]
it has been fixed in #225
