### ISSUE TITLE
Timer Clock on KeyGen

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#212]
# User should feel progress on keygen

1) Clock ARC, which "winds" towards 12-oclock

prepare: 10 seconds
ECDSA: 10 seconds
EdDSA: 10 seconds
DONE: 1 second animation

2) Clock ARC should slow down in the last ¼ arc, gradually "inching" towards 12-oclock until the step is complete, but not finishing until step complete
3) Clock ARC should instantly speed up and fill when progressing to next STEP

4) words while waiting

"Generating ECDSA Key"
line underneath scrolls all ECDSA chains (while waiting)
<<<<<< Bitcoin, Ethereum, Litecoin, Dogecoin..... <<<<

"Generating EdDSA Key"
line underneath scrolls all EdDSA chains:
<<<<<< Solana, Polkadot, Aptos..... <<<<

![image](https://github.com/voltix-vault/voltix/assets/41815753/6619ed8d-e443-4317-8a8d-90bb46e62e0d)

5) DONE

User should be presented with a DONE animation

- clock arc morphs into giant TICK ✅
- animation!
- maybe logo pulses

max 2 seconds

**Comment by johnnyluo** [comment]
Discuss the design with Mia when you start it @Rockindash
