### ISSUE TITLE
[FEATURE] Allow the app to display in other currencies

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix#218]
Currently the app hard coded the price in USD value , and there are many functions to convert crypto balance to USD value , we need to update it to convert to target currency.
1. User can choose their preferred currency in settings, default one will be USD
 
<img width="887" alt="image" src="https://github.com/voltix-vault/voltix/assets/749608/ac074cf2-b077-40d0-a160-eabf47a48a75">
2. Update the app to convert to the chosen target currency
3.  Try to centralised the function that convert crypto balance to a few functions instead of having it in many places.

**Comment by enriquesouza** [comment]
I will handle it

**Comment by enriquesouza** [comment]
PR 220 fix that.
