### ISSUE TITLE
Iphone stuck on "Discovering mediator service"

### ISSUE THREAD

**Issue by zeymermontes** [voltix-vault/voltix#221]
While trying to create a new vault from mac, when scanning on iPhone  the screen gets stuck on the following:
![20240408_005925](https://github.com/voltix-vault/voltix/assets/66459565/6f7506b3-ce78-4545-ae8f-1d2b2f43f815)

**Comment by johnnyluo** [comment]
Thanks for reporting this @zeymermontes 
1. is your mac and iphone on the same wifi network?  
2. When you launch your voltix app , it should ask your permission to discover local network , did you click "allow" ?   If not you can change it in settings -> privacy & security -> Local Network

**Comment by johnnyluo** [comment]
@zeymermontes , this is highly likely your network doesn't allow mDNS  , you could try to tick "Cellular" option when creating vault. 

Cellular option was added at build 21 , you need to get the latest version
