### ISSUE TITLE
[BUG] - Choose chains / Add coins

### ISSUE THREAD

**Issue by enriquesouza** [voltix-vault/voltix#245]
The children are not being shown while adding or removing new coins

<img width="510" alt="image" src="https://github.com/voltix-vault/voltix/assets/1700699/0831e51c-83e2-4eeb-94bd-d2a541879df2">

**Comment by johnnyluo** [comment]
When you click "choose chain" button , it suppose to just show the coins that are native to the blockchain . 
For example , only ETH will be show for Ethereum , **NONE** of the ERC20 will be displayed 
when you get to detail view, and click "choose tokens" , then it will display all the ERC20 tokens

**Comment by enriquesouza** [comment]
Yes, I've retested it now and it seems ok, the flow changed, I had to delete my vaults and re-add them.
