### ISSUE TITLE
[ Improvement ] - Price alternative api 

### ISSUE THREAD

**Issue by enriquesouza** [voltix-vault/voltix#250]
If coingecko fails we need to have alternatives to bring the price. So I will implement more than one price feed like Coinpaprika and Coin market cap.

**Comment by johnnyluo** [comment]
Do CoinMarketcap , we might switch from coingecko to Coinmarketcap , it is cheaper

There is no point to add CoinPaprika , since we have to pay for the api, and we will only pay for one.

**Comment by enriquesouza** [comment]
I can add it as well, CoinPaprika gives 20k calls per month. 

Free
CURRENTLY SELECTED
0$/mo
For personal projects of all kinds
20 000 calls/mo

I am fetching all coins in a single call and caching it. It means we have 20k calls per user without API KEY. So it will be by IP, probably it is better to use this one as the main one instead of Coingecko. So we won't need to pay to any of them since the calls come from the user's device IP.
