### ISSUE TITLE
ADD: WiFi | HotSpot | Cellular Prompts

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#254]
# Context

Voltix does not work on most hotel/airport wifi - poor UX, user should be given options. 

# Desired

Prompt user to use different connection options. This is just UX buttons, it does not do anything to the protocol. 

<img width="249" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/364a0e18-2952-4446-87a6-8db46a126d9f">

```
WiFi
Keep all devices on same WiFi with Voltix App open. (May not work on hotel/airport wifi).

Hotspot
Connect all devices to the same Personal Hotspot with Voltix App open.

Cellular
Connect all devices to the internet with the Voltix App open.
```

<img width="394" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/001b7557-ed27-4a84-a256-001c72ca5bb0">

**Comment by johnnyluo** [comment]
The term here `Wifi` `hotspot` `Cellular` is confusing ,  
We should just show a toggle `voltix router` ,  when it is on , the app will route the traffic through voltix router server ,  when it is off , it will communicate with each other locally. 

When the hotel wifi which block mDNS  , user can use voltix router

**Comment by johnnyluo** [comment]
@Rockindash when user check `Cellular` , please set `VoltixRouter.IsRouterEnabled` to true , the barcode should be updated as well , in this way , the traffic will go through voltix router

**Comment by johnnyluo** [comment]
@Rockindash  we need the same options at keysign as well
