### ISSUE TITLE
ADD: Voltix Premium

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#255]
# Context

Voltix Premium
- Remote Signing via Cellular
- 3rd/4th Device Backups (optional)
- Transaction Policy

$99/mo via Apple Subscription Service. 

# Premium
For KeySign via Cellular (let anyone KeyGen via Cellular to get them into the app). 

- [x] Add KeyGen | KeySign ID in p2p to identify which it is
- [x] TSS Relay Server
- [x] Client Encryption
- [ ] KeySign Subscription Check
- [ ] Subscribe Button

# Subscribe
For now, when someone subscribes, they are just putting in a redemption code (eg `alpha`). 
Send this to Relay, do check, add public key to DB as a subscriber. 
Now is subscriber.

Later
- Subscribe via Apple Sub / credit card
- Subscribe by making a crypto payment to Voltix Admin address
- etc

**Comment by johnnyluo** [comment]
Given we decided to not charge for premium features , so the relay server we will call it voltix router , it will be free for user to use, but there will have an option

The router server is ready , thus I will close this issue
