### ISSUE TITLE
ADD: Faster Signing

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#262]
# Pre-processing

1) Do keysign pre-processing whilst reviewing transaction data, have it ready
2) then keysign is faster

Will need to split keysign into two rounds `prepareKeysign()` and then `finishKeysign()`

**Comment by johnnyluo** [comment]
I am going to close this one , as it is not possible for TSS to do this right now , TSS keysign is interactive , can't presign stuff
