### ISSUE TITLE
UI: Small fixes

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix#269]
# Vaults View
- [x] Default to picking the first vault; (or picking the last vault opened)
- [x] Save last selected vault preference
- [x] Vault View list title "VAULTS" (not "Main")
- [x] Top right "Refresh" button, not needed. Use `edit` and allow to re-arrange order of vaults. 
- [x] remove "edit" button from the row

<img width="549" alt="Screenshot 2024-04-17 at 8 30 05 am" src="https://github.com/voltix-vault/voltix/assets/41815753/e35ea1d8-23e6-4b40-a610-d6b4b164f95a">

# Vault View

- [x] remove "refresh" button top right
- [x] replace with "edit" button to edit the vault

<img width="599" alt="Screenshot 2024-04-17 at 8 30 39 am" src="https://github.com/voltix-vault/voltix/assets/41815753/d8f3460e-366f-42a9-81fb-2fb369fe0db9">

# Device Name
- [x] use 3-digits (not 12-digits), too hard to read (everywhere)
- [x] device-name add to end of vault-backup file name `{vaultDetails}-{deviceName}.dat`

<img width="325" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/88a08fec-67fe-404c-86a4-0b4c825cd6d1">

<img width="467" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/29aedbe7-f207-4e3b-8f68-1955dab45e80">

# Chains
- [x] Add BSC to default chain list

# Chain View
- [x] Icon for "transaction history" confusing - use an up-right arrow `square.and.arrow.up` style icon
- [x] re-order icons `copy | QR | link`

<img width="516" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/89f62d59-ce76-42e7-827f-a4bdb3ce8907">

# Send View
- [x] Allow to dismiss keyboard always (to review) `chevron.down.square` right of `continue` button

# Swap View
- [x] Allow to dismiss keyboard always (to review) `chevron.down.square` right of `continue` button

<img width="449" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/3729cfad-a0cb-4349-bfd0-1b9e9d930ae3">

**Comment by Runetard** [comment]
<img width="1511" alt="Screenshot 2024-04-20 at 12 53 56 PM" src="https://github.com/voltix-vault/voltix/assets/166342714/4bc3b2b4-60ea-48a8-a496-6c36ae163b06">

Some other UI musings.
