### ISSUE TITLE
Allow joining from mac mini / studio

### ISSUE THREAD

**Issue by hewigovens** [voltix-vault/voltix#271]
Hey guys, I tested Voltix on an m1 mac mini which doesn't have a builtin camera

<img width="1136" alt="image" src="https://github.com/voltix-vault/voltix/assets/360470/7e9ecca4-b90a-4770-a25c-880f29fe9b1f">

Could you please add options to scan from camera or paste from clipboard? low priority is fine to me

**Comment by johnnyluo** [comment]
Can you use your mac mini as the main device?  The one you initiate create vault?

**Comment by hewigovens** [comment]
Yes, that's how I did at last. But I would still like to use my iPhone as main device because it's more accessible than the mac mini

**Comment by jpthor** [comment]
We can add a "import from file/screenshot" instead
1) Screenshot
2) Airdrop to Mac mini
3) Upload.

**Comment by jpthor** [comment]
> Yes, that's how I did at last. But I would still like to use my iPhone as main device because it's more accessible than the mac mini

It actually doesn't matter which device is main; you can start/finish on either one. They are both equivalent
