### ISSUE TITLE
Bug: RUNE Tx showing "EDDSA"

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix#290]
When executing a RUNE Tx, the app (wrongly?) showing it's a EDDSA Tx.

<img width="161" alt="image" src="https://github.com/voltix-vault/voltix/assets/96066776/6f73a5ef-b797-4598-854c-a84872bef61f">

**Comment by johnnyluo** [comment]
Yup, it should be ECDSA

**Comment by johnnyluo** [comment]
Just tried , mine is correct
<img width="594" alt="image" src="https://github.com/voltix-vault/voltix/assets/749608/5e8afdcd-9136-41c8-a503-6a3310238622">

**Comment by johnnyluo** [comment]
are you sure you are not signing Solana @SamYap0 ?

**Comment by SamYap0** [comment]
My bad!
I tried again, and I see ECDSA now. 
Damn, sorry for my sleepy eyes!
